name: "tool-searching"
tool_command: "python"
args:
  - "-m"
  - "src.tool.mcp_servers.search_and_scrape_webpage"
env:
# Search API keys - these values will be loaded from the .env file at runtime
  SERPER_API_KEY: "${oc.env:SERPER_API_KEY}"
  TENCENTCLOUD_SECRET_ID: "${oc.env:TENCENTCLOUD_SECRET_ID}"
  TENCENTCLOUD_SECRET_KEY: "${oc.env:TENCENTCLOUD_SECRET_KEY}"