defaults:
  - benchmark: example_dataset
  - override hydra/job_logging: none
  - _self_

main_agent:
  prompt_class: MainAgentPromptBoxedAnswer
  llm:
    provider_class: "MiroThinkerSGLangClient"
    model_name: "miromind-ai-mirothinker-v1.0-8b-mlx"
    async_client: true
    temperature: 0.6
    top_p: 0.95
    min_p: 0.0
    top_k: -1
    max_tokens: 262144
    oai_mirothinker_api_key: "${oc.env:OAI_MIROTHINKER_API_KEY,lm-studio}"
    oai_mirothinker_base_url: "${oc.env:OAI_MIROTHINKER_BASE_URL,http://127.0.0.1:1234/v1}"
    keep_tool_result: -1
    oai_tool_thinking: false

  tool_config:
    - tool-reading

  max_turns: 20
  max_tool_calls_per_turn: 10

  input_process:
    hint_generation: false
    hint_llm_base_url: "${oc.env:HINT_LLM_BASE_URL,https://api.openai.com/v1}"
  output_process:
    final_answer_extraction: false
    final_answer_llm_base_url: "${oc.env:FINAL_ANSWER_LLM_BASE_URL,https://api.openai.com/v1}"

  openai_api_key: "${oc.env:OPENAI_API_KEY,dummy}"
  add_message_id: true
  keep_tool_result: -1
  chinese_context: "${oc.env:CHINESE_CONTEXT,false}"

sub_agents: null

output_dir: logs/
data_dir: "${oc.env:DATA_DIR,data}"
